/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103543-gc655a734b1-20210907"
#endif /* AVUTIL_FFVERSION_H */
